"""Close the knowledge loop: write each mission run back into wiki/synthesis/.

Honors the schema in wiki/AGENTS.md:
- Synthesis page frontmatter: type: synthesis, tags
- Wikilinks (never markdown hyperlinks) for internal references
- index.md updated under "## Mission runs" (created if missing)
- log.md appended with `## [YYYY-MM-DD] <type> | <title>` header per spec
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from firefly.orchestrator import MissionRequest

WIKI_ROOT = Path(__file__).resolve().parent.parent.parent.parent / "wiki"
SYNTHESIS_DIR = WIKI_ROOT / "synthesis"
INDEX_FILE = WIKI_ROOT / "index.md"
LOG_FILE = WIKI_ROOT / "log.md"

_MISSION_RUNS_HEADER = "## Mission runs"


def _synthesis_filename(req: "MissionRequest", today: dt.date) -> str:
    return f"odc-mission-{req.slug()}-{today.isoformat()}.md"


def _render_page(req: "MissionRequest", collated: dict, brief_md: str) -> str:
    today = dt.date.today().isoformat()
    return (
        "---\n"
        "type: synthesis\n"
        "tags: [odc, mission-plan, orbit, radiation, firefly]\n"
        f"date: {today}\n"
        "generator: firefly (unified-firefly mvp)\n"
        "---\n\n"
        f"# ODC Mission — {req.from_} → {req.to} ({req.window})\n\n"
        f"Generated by [[entities/sampras]]'s [[concepts/domain-specific-llm-agents|Firefly agent]] on {today}.\n\n"
        "## Knowledge base used\n\n"
        "- [[concepts/orbit-dose-budgeting]]\n"
        "- [[concepts/rha-radiation-hardening]]\n"
        "- [[concepts/cots-gpu-radiation-risk]]\n"
        "- [[concepts/orbital-data-center]]\n"
        "- [[concepts/see-single-event-effects]]\n"
        "- [[concepts/tid-total-ionizing-dose]]\n\n"
        "## Mission brief\n\n"
        f"{brief_md}\n\n"
        "---\n\n"
        "*This page was auto-filed by `agents/src/firefly/wiki_writer.py` "
        "to close the knowledge loop — see plan "
        "`nemo-agent-toolkit-unified-firefly.md`.*\n"
    )


def _ensure_index_section() -> str:
    """Read index.md and ensure '## Mission runs' section exists."""
    text = INDEX_FILE.read_text(encoding="utf-8") if INDEX_FILE.exists() else ""
    if _MISSION_RUNS_HEADER not in text:
        text = text.rstrip() + "\n\n" + _MISSION_RUNS_HEADER + "\n\n"
    return text


def _append_index_entry(req: "MissionRequest", page_slug: str, today: dt.date) -> None:
    text = _ensure_index_section()
    entry = (
        f"- [[synthesis/{page_slug}]] — ODC mission plan {req.from_} → {req.to} "
        f"({req.window}), filed by firefly on {today.isoformat()}\n"
    )
    # Insert right after the Mission runs header (keeps newest first).
    parts = text.split(_MISSION_RUNS_HEADER, 1)
    head, tail = parts[0], parts[1]
    tail_stripped = tail.lstrip("\n")
    text = head + _MISSION_RUNS_HEADER + "\n\n" + entry + tail_stripped
    INDEX_FILE.write_text(text, encoding="utf-8")


def _append_log_entry(req: "MissionRequest", page_slug: str, today: dt.date) -> None:
    """Append per wiki/AGENTS.md format: '## [YYYY-MM-DD] <type> | <title>'."""
    if not LOG_FILE.exists():
        return
    entry = (
        f"\n## [{today.isoformat()}] query | firefly ODC mission plan "
        f"({req.from_} → {req.to}, {req.window})\n"
        f"Generated [[synthesis/{page_slug}]] via the unified-firefly agent "
        f"(OrbitDesignerAgent real; LaunchPlanner/PowerThermal/Risk/Narrator stubbed). "
        f"Wiki KB context: orbit-dose-budgeting, rha-radiation-hardening, "
        f"cots-gpu-radiation-risk, orbital-data-center, see-single-event-effects, "
        f"tid-total-ionizing-dose.\n"
    )
    with LOG_FILE.open("a", encoding="utf-8") as fh:
        fh.write(entry)


def write_synthesis(req: "MissionRequest", collated: dict, brief_md: str) -> Path:
    """Write synthesis page + update index + append log. Returns the page path."""
    today = dt.date.today()
    SYNTHESIS_DIR.mkdir(parents=True, exist_ok=True)

    fname = _synthesis_filename(req, today)
    page_slug = fname.removesuffix(".md")
    page_path = SYNTHESIS_DIR / fname
    page_path.write_text(_render_page(req, collated, brief_md), encoding="utf-8")

    if INDEX_FILE.exists():
        _append_index_entry(req, page_slug, today)
    _append_log_entry(req, page_slug, today)

    return page_path
