"""Close the knowledge loop: write each research run back into wiki/synthesis/.

Mirrors firefly.wiki_writer:
  - Synthesis page in `wiki/synthesis/trade-<ticker>-<YYYY-MM-DD>.md`
  - Frontmatter: type: synthesis, tags including [trading, equity, llm-analyst, <ticker>]
  - Index update under a "## Trading research" section (created if missing)
  - log.md appended with `## [YYYY-MM-DD] research | <ticker> | LLM_BACKEND=<...>`

If `wiki/` doesn't exist (e.g. tests in tmp dirs), silently no-ops.
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from trader.schemas import ResearchRequest, TradeThesis


WIKI_ROOT = Path(__file__).resolve().parent.parent.parent.parent / "wiki"
SYNTHESIS_DIR = WIKI_ROOT / "synthesis"
INDEX_FILE = WIKI_ROOT / "index.md"
LOG_FILE = WIKI_ROOT / "log.md"

_TRADING_RUNS_HEADER = "## Trading research"


def _synthesis_filename(req: "ResearchRequest", today: dt.date) -> str:
    return f"trade-{req.slug()}-{today.isoformat()}.md"


def _render_page(
    req: "ResearchRequest",
    thesis: "TradeThesis | None",
    brief_md: str,
    backend_name: str,
) -> str:
    today = dt.date.today().isoformat()
    abstained = bool(thesis and thesis.abstain)
    tag_extras = ["abstain"] if abstained else []
    tag_list = ["trading", "equity", "llm-analyst", req.ticker.lower(), *tag_extras]
    return (
        "---\n"
        "type: synthesis\n"
        f"tags: [{', '.join(tag_list)}]\n"
        f"date: {today}\n"
        f"generator: trader (yxz-agents v0.1)\n"
        f"llm_backend: {backend_name}\n"
        "---\n\n"
        f"# {req.ticker} — LLM Analyst Brief ({today})\n\n"
        f"Generated by [[entities/sampras]]'s `trader` agent on {today}, "
        f"using the LLM_BACKEND `{backend_name}` configuration.\n\n"
        "## Knowledge base used\n\n"
        "- [[synthesis/ai-quant-trading-architecture-improvements]]\n"
        "- [[concepts/calibrated-confidence-llm]]\n"
        "- [[concepts/agentic-provenance]]\n\n"
        "## Brief\n\n"
        f"{brief_md}\n\n"
        "---\n\n"
        "*This page was auto-filed by `agents/src/trader/wiki_writer.py` "
        "to close the knowledge loop. v1 is analysis-only — no orders are "
        "executed. See plan parking lot for the v2 execution-hook interface.*\n"
    )


def _ensure_index_section() -> str:
    text = INDEX_FILE.read_text(encoding="utf-8") if INDEX_FILE.exists() else ""
    if _TRADING_RUNS_HEADER not in text:
        text = text.rstrip() + "\n\n" + _TRADING_RUNS_HEADER + "\n\n"
    return text


def _append_index_entry(
    req: "ResearchRequest", page_slug: str, today: dt.date, thesis: "TradeThesis | None"
) -> None:
    text = _ensure_index_section()
    verdict = "abstain" if (thesis and thesis.abstain) else (thesis.direction.value if thesis else "?")
    entry = (
        f"- [[synthesis/{page_slug}]] — {req.ticker} LLM analyst brief "
        f"({today.isoformat()}, verdict: {verdict})\n"
    )
    parts = text.split(_TRADING_RUNS_HEADER, 1)
    head, tail = parts[0], parts[1]
    text = head + _TRADING_RUNS_HEADER + "\n\n" + entry + tail.lstrip("\n")
    INDEX_FILE.write_text(text, encoding="utf-8")


def _append_log_entry(
    req: "ResearchRequest", page_slug: str, today: dt.date, backend_name: str
) -> None:
    if not LOG_FILE.exists():
        return
    entry = (
        f"\n## [{today.isoformat()}] research | {req.ticker} | LLM_BACKEND={backend_name}\n"
        f"Generated [[synthesis/{page_slug}]] via the `trader` agent. "
        "Implements perception → brain → execution from "
        "[[synthesis/ai-quant-trading-architecture-improvements]] (v1 is analysis-only; "
        "execution layer parked).\n"
    )
    with LOG_FILE.open("a", encoding="utf-8") as fh:
        fh.write(entry)


def write_synthesis(
    req: "ResearchRequest",
    thesis: "TradeThesis | None",
    brief_md: str,
    backend_name: str,
) -> Path | None:
    """Write synthesis page + update index + append log. Returns the page path or None."""
    if not WIKI_ROOT.exists():
        return None
    today = dt.date.today()
    SYNTHESIS_DIR.mkdir(parents=True, exist_ok=True)

    fname = _synthesis_filename(req, today)
    page_slug = fname.removesuffix(".md")
    page_path = SYNTHESIS_DIR / fname
    page_path.write_text(
        _render_page(req, thesis, brief_md, backend_name), encoding="utf-8"
    )

    if INDEX_FILE.exists():
        _append_index_entry(req, page_slug, today, thesis)
    _append_log_entry(req, page_slug, today, backend_name)

    return page_path
