name: Deploy Docusaurus

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-website  # 指定工作目錄

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 根據你的需求選擇 Node 版本

      - name: Install dependencies
        run: yarn install

      - name: Deploy website
        run: yarn deploy
